version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db
    networks:
      - resp_tracker_network

  backend:
    build:
      context: ./
    container_name: backend_server
    environment:
      - PORT=3001
      - DB_CONN_STRING=mongodb://mongo:27017/resp_tracker
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - resp_tracker_network
    command: npm run prod

networks:
  resp_tracker_network:
    driver: bridge

volumes:
  mongo-data:
